---
# tasks file for get-rhcos-template
- name: Create Directory
  file:
    path: "{{ base_dir }}//.rhcos"
    state: directory
- name: Get RHCOS OVA
  command: "curl -s https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/latest/latest/rhcos-vmware.x86_64.ova -o {{ base_dir }}/.rhcos/rhcos-vmware.x86_64.ova"
- name: Remove old template
  community.vmware.vmware_guest:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    validate_certs: no
    datacenter: "{{ vsphere.datacenter }}"
    name: "rhcos-template"
    state: absent
  delegate_to: localhost
- community.vmware.vmware_deploy_ovf:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    datacenter: "{{ vsphere.datacenter }}"
    cluster: "{{ vsphere.cluster }}"
    datastore: "{{ vsphere.datastore }}"
    networks: "{u'VM Network':u'{{ vsphere.network }}'}"
    name: "rhcos-template"
    power_on: no
    ovf: "{{ base_dir }}/.rhcos/rhcos-vmware.x86_64.ova"
  delegate_to: localhost
- name: Create template
  community.vmware.vmware_guest:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere.password }}"
    validate_certs: no
    datacenter: "{{ vsphere.datacenter }}"
    name: "rhcos-template"
    is_template: yes
  delegate_to: localhost
